export const CloudinaryResourceType = {
    SALON_COVER: 'SALON_COVER',
    SALON_GALLERY: 'SALON_GALLERY',
    STYLIST_PROFILE: 'STYLIST_PROFILE',
    STYLIST_PORTFOLIO: 'STYLIST_PORTFOLIO',
    SERVICE_THUMBNAIL: 'SERVICE_THUMBNAIL',
    CATEGORY_THUMBNAIL: 'CATEGORY_THUMBNAIL',
    PARTNER_DOCUMENT: 'PARTNER_DOCUMENT',
    STATIC: 'STATIC',
};
